experimental_info:
  sub: 'hoge'
  shedule: 'fuga'
  session: 9999
  med: 'foo'

signal_info:
  width: 500
  height: 100
  radius: 20

color_01:
  color_R: 255
  color_G: 0
  color_B: 0

color_02:
  color_R: 0
  color_G: 255
  color_B: 0

color_03:
  color_R: 0
  color_G: 0
  color_B: 255

color_04:
  color_R: 255
  color_G: 255
  color_B: 0

arduino:
  port: 'COM9'
  serial_baudrate : 9600
  pin_num: 4
